[#silent-worship, short="Testimony to Silent Worship"]
== A Testimony to the Silent Worship of God, In Spirit and In Truth.

I have considered it a duty I owe to my great Creator and my fellow creatures,
to commit to writing some of my own experience respecting silent worship.
"`God is a spirit;`" and according to the declaration of his beloved son,
"`they that worship him must worship him in spirit and in truth:
for the Father seeketh such to worship him.`"

Now, in relating my experience concerning this silent adoration of the Supreme Being,
I have not the least doubt that I communicate the experience
of thousands who have fallen asleep in Christ,
and of many that are still in the body.

It pleased the Lord to visit my soul with the day spring from on high,
in the sixteenth year of my age; when, from day to day,
he broke in upon me with the over-shadowings of his love,
causing me to rejoice in his salvation--melting
my heart and contriting my spirit before him,
and making known to me, through the medium of his Holy Spirit,
what to do and what to leave undone.
Although from much younger life, I sometimes felt his powerful spirit at work in my soul,
yet now in the fall of the year 1773, it became a daily visitation,
and has so continued ever since;
notwithstanding I have not every day enjoyed the like spiritual consolations,
as in the day of my espousals unto Christ, my sovereign Lord.
Though many a bitter cup of poverty and suffering hath been wisely dispensed to me,
yet as the word of God`'s patience hath been abode in,
these seasons of probation and refining have been succeeded by
times of refreshment from the presence of the Lord.

In these early visitations of heavenly love,
I went to meetings in a very different state of
mind from what I had done in the time preceding.
I felt the Beloved of my soul to draw my attention from every worldly thought,
and to centre my mind on him, the object of my adoration and praise.
Even when eminent ministers attended our meeting,
I felt restrained by the Holy Spirit from indulging a
wish to hear the gospel publicly preached;
but secretly and fervently was I engaged to pray
unto the Lord for help to draw nigh unto him,
and worship him acceptably, in spirit and in truth.
He begat these prayers in my heart, and he answered them;
again and again lifting up the light of his
blessed and glorious countenance upon my soul,
and preparing the offerings of praise and thanksgiving with
much tenderness and brokenness of spirit before him.

Here I was fed with the bread of life,
which nourishes and strengthens the Lord`'s children.
I enjoyed what those valuable messengers of the Lord partook of
before they rose to minister to the people--even the presence of the
great I AM. He made himself known by the breaking of bread;
he gave us to drink of the new wine of his kingdom; he satisfied our souls with his love.
Being gathered together in the name of Christ,
those ministers were anointed to preach the gospel to the people,
in the demonstration of the spirit, and with power.
The precious savour of life attending their ministry,
and uniting with the same Divine influence in my heart,
like face answering face in a glass,
tended to strengthen and build me up in the most holy faith.
Thus in the silent part of the meeting, previous to any vocal testimonies,
pure and spiritual worship was performed to him who lives forever,
and my soul was edified and refreshed.
Blessed be the Lord my God, who hath made me and thousands more,
experimental witnesses of his life-giving presence,
in those seasons of holy sequestration from every earthly object.
A holy, spiritual communion with the Father and the son, hath been abundantly witnessed,
and our souls have abounded with thanksgiving
and praises to him who sitteth upon the throne,
and to the Lamb, who is worthy thereof forever more.
Amen.

After some years`' experience in this silent, spiritual worship,
I felt a necessity publicly to espouse the cause of truth and righteousness.
But I dared not engage in this very important work of the ministry,
without gathering into the name of Christ,
and waiting to feel his power and presence to warm my heart,
and influence it with the love of the gospel.
Here, in reverential silence before the Lord, a renewed qualification hath been given,
from time to time, to preach the glad tidings of redeeming grace.
Many times previous to appointing meetings amongst those not professing with us,
I have been tried with great inward poverty.
But, as I never determined in my mind, beforehand,
that I would preach when I came to the meeting, and being utterly unprepared as to words,
I have sat down with my mind turned inward to the Lord in mental prayer,
knowing that without him I could do nothing;
and he hath graciously appeared in my silent waiting,
furnishing me with strength and ability to offer matter, suitable I trust,
to the states of many or most present.
For unless I had felt his blessed presence to strengthen and qualify me,
I would rather have laid down my life,
than have attempted to minister to the people by virtue of any parts or abilities,
natural or acquired, which, as a man, I might possess.
So that I have always found it necessary to be engaged in silent worship, for a season,
before public preaching or praying, in the assemblies of the people.

"`The preparation of the heart in man, and the answer of the tongue is from the Lord.`"
And again, "`They that wait upon the Lord shall renew their strength:
they shall mount up with wings, as eagles: they shall run and not be weary,
and they shall walk and not faint.`"
A blessed and glorious privilege indeed! realized, in an especial manner,
in the experience of those who have none but the Lord for their helper.

Great is the loss sustained by those who profess to be ministers of the gospel,
for want of patiently waiting for the necessary
qualification of being endued with power from on high,
before they attempt to utter gospel truths to the people.
Such is the present degenerated custom, that,
however many acknowledge the excellency of being actuated by the holy spirit,
in matters purely religious, they do not avail themselves of it,
by humbly and patiently waiting upon the Lord, for the aid thereof.
A person of this class once said to me, "`I have often been ashamed,
when I have arisen off my knees, in meetings: have not you!`"
I told him no: and asked what made him ashamed.
"`Because (said he) my mind was upon the things of the world, whilst at prayer.`"
I told him there was a cause for that.
Thou did not wait upon the Lord, to feel the spirit of prayer, poured out upon thee.
That would have kept thy mind from wandering upon the things of the world,
and would have fixed it upon the true object of adoration.
It would have been better for thee, not to have attempted to appear in prayer,
at those times.
A lamentable acknowledgment indeed!--mere mockery A form of godliness,
without the power! and that which could not profit,
but might do a real injury to the people,
by setting them down in an empty form of worship.

"`This people draweth nigh unto me with their mouth, and honoureth me with their lips,
but their heart is far from me,`" was a complaint of the Most High, formerly,
and may include all such as do not experience the power
of Divine love to influence their hearts,
and enable them to worship the Lord in the beauty of holiness.

Another person informed me, with apparent concern,
that divers times he had felt utterly unfit for the sacred work of preaching,
for want of feeling the influence of the Holy Spirit; and yet, in that state,
he went through the service, because the people expected it.
A third said, he felt more like falling down on the floor than preaching,
and that he would rather have been following the plough.

It is clear and evident,
that in such momentous concerns the Lord`'s presence ought to be waited for,
to enable the preacher to speak in the demonstration of the spirit and with power,
and to baptize the hearers, so that they might be strengthened and edified together.

If people were but acquainted with this inwardly drawing nigh unto God, or as Paul said,
"`Seek the Lord, if haply they might feel after him and find him,
though he be not far from every one of us;`" no, verily, he is near us, he is in us,
by his Holy Spirit they would be much less anxious to hear preaching.
Being gathered under the healing wings of the Prince of peace,
and having bread in their own houses, and water in their own cisterns,
what more could they desire?
In this state of mind they would often be favoured with
a blessed assurance that their sins were forgiven,
and that their souls were brought into a state of acceptance with God, their Creator.
All fears and doubts would be removed,
and renewed cause would often be given to magnify the Lord,
and to rejoice in God their Saviour.

William Law, who wrote largely, in an instructive manner, on many religious subjects,
hath these words: "`To speak with the tongues of men or angels on religious subjects,
is a much less thing than to know how to stay the mind upon God,
and abide with him in the closet of our hearts, observing, loving,
adoring and obeying his holy power within us.`"
Again, he says: "`I hurt myself, and am only acting a part,
if I speak to persons on spiritual matters, either sooner or further,
than the Spirit of God (which bloweth when and where it listeth) would be resisted in me,
if I held my peace.`"
And Bernard saith: "`All prayer is lukewarm,
which hath not an inspiration preceding it.`"

It hath not unfrequently happened, among some professing Christians,
that when their preacher has been indisposed,
or on some other account absent from his place of worship,
that the meeting has been discontinued.
What a pity that so great dependence has been put upon one man;
as though his presence was indispensable in
performing spiritual worship to the Most High;
as though that blessed declaration of Christ could not
be realized unless the preacher was present,
"`Where two or three are gathered together in my name,
there am I in the midst of them.`"--Surely,
it appears too much like limiting the Holy One of Israel.

Now, if the people in those places had been acquainted with,
and delighted in gathering or turning the mind inward to feel after God,
they might have sat together, and no doubt often would sit together,
in heavenly places in Christ Jesus,
and know their hearts divinely prepared to worship and adore the Majesty in the heavens,
and be much more spiritually refreshed and strengthened,
than to hear the best words that man could utter.

Preaching, under the influence of the Holy Spirit, is good, and a blessing to the church;
but, persuaded I am,
that if the people generally were disposed to receive
strength from the pure Fountain of everlasting love,
opened in their hearts, there would be but little necessity for it.
Many instances have doubtless occurred of people living far
from any who were considered ministers of the gospel,
and have been visited with great bodily indisposition,
so that their dissolution has been fully expected--to whom then could they apply,
but to the Lord alone, who is a God hearing prayer.
And as they have fervently sought him, as upon the bended knees of their souls,
surely he hath heard their secret cries,
and granted them their hearts`' desire--even peace, sweet, heavenly peace,
and an assurance that their sins were washed away by the blood of the Lamb.

Such is the nature, such the blessed effects, of cherishing an intercourse with Heaven.
Truly, the advantages are unspeakable.
Would to God, that the people, everywhere, delighted therein; and,
by yielding up their hearts to God, in the first place, they would often,
from day to day, out of meeting as well as in meetings,
have a spiritual communion with Him, who is the chiefest of ten thousands.
An evidence, renewed from time to time, would be granted them,
that when their warfare here on earth is accomplished,
they will be admitted to join the innumerable company of the heavenly host,
in ascribing blessing and praise, glory and honour,
unto Him that sitteth upon the throne, and unto the Lamb forever.

Amen.

[.signed-section-signature]
Isaac Martin.

[.signed-section-context-close]
Bridgetown, Rahway, East New Jersey, 9th mo. 27th 1819
